### ISSUE TITLE
Composite encoding with Grid

### ISSUE THREAD

**Issue by diolatzis** [NVlabs/tiny-cuda-nn#57] opened 2022-03-05 19:15 UTC
Hi Thomas,

Thanks for sharing this code it's super helpful. 

Is combining the Grid encoding with other encodings using Composite not supported? When I add the Grid encoding in a Composite encoding for the 3 first dimension I get a `RuntimeError: CUDA error: an illegal memory access was encountered` while if I replace it with a Frequency encoding the code works. 

My config is:

```{
	"loss": {
		"otype": "RelativeL2"
	},
	"optimizer": {
		"otype": "Adam",
		"learning_rate": 1e-2,
		"beta1": 0.9,
		"beta2": 0.99,
		"epsilon": 1e-15,
		"l2_reg": 1e-6
	},
	"encoding":	{
		"otype": "Composite",
		"nested": [
			{
				"n_dims_to_encode": 3,
				"otype": "Grid",           // Component type.
				"type": "Hash",            // Type of backing storage of the
										   // grids. Can be "Hash", "Tiled"
										   // or "Dense".
				"n_levels": 16,            // Number of levels (resolutions)
				"n_features_per_level": 2, // Dimensionality of feature vector
										   // stored in each level's entries.
				"log2_hashmap_size": 19,   // If type is "Hash", is the base-2
										   // logarithm of the number of elements
										   // in each backing hash table.
				"base_resolution": 16,     // The resolution of the coarsest le-
										   // vel is base_resolution^input_dims.
				"per_level_scale": 2.0,    // The geometric growth factor, i.e.
										   // the factor by which the resolution
										   // of each grid is larger (per axis)
										   // than that of the preceeding level.
				"interpolation": "Linear"  // How to interpolate nearby grid
										   // lookups. Can be "Nearest", "Linear",
										   // or "Smoothstep" (for smooth deri-
										   // vatives).
			},
			{
				"otype": "Identity"
			}

		]
	},
	"network": {
		"otype": "FullyFusedMLP",
		"activation": "ReLU",
		"output_activation": "None",
		"n_neurons": 64,
		"n_hidden_layers": 5
	}
}
```

Thanks in advance!

**Comment by Tom94** [comment] 2022-03-06 07:32
Hi Stavros, that's strange -- it _should_ work. I quickly tried your config in our radiance caching code and it works fine on my machine.

For reference, here's the config we used in the paper:
```json
{
    "loss": {
        "otype": "RelativeL2Luminance"
    },
    "optimizer": {
        "otype": "Ema",
        "decay": 0.99,
        "sensitivity": 0.1,
        "nested": {
            "otype": "ExponentialDecay",
            "decay_start": 4000,
            "decay_interval": 4000,
            "decay_base": 0.33,
            "nested": {
                "otype": "Adam",
                "learning_rate": 1e-2,
                "beta1": 0.9,
                "beta2": 0.99,
                "epsilon": 1e-15,
                "l2_reg": 1e-6
            }
        }
    },
    "encoding": {
        "otype": "Composite",
        "nested": [
            {
                "n_dims_to_encode": 3, // Position
                "otype": "HashGrid",
                "per_level_scale": 2.0,
                "log2_hashmap_size": 15,
                "base_resolution": 16,
                "n_levels": 16
            },
            {
                "n_dims_to_encode": 5, // Interesting conditionals
                "otype": "OneBlob",
                "n_bins": 4
            },
            {
                "n_dims_to_encode": 6, // Linear conditionals that should be identity encoded
                "otype": "Identity"
            }
        ]
    },
    "network": {
        "otype": "FullyFusedMLP",
        "activation": "ReLU",
        "output_activation": "None",
        "n_neurons": 64,
        "n_hidden_layers": 2
    }
}
```

To troubleshoot further:
- could you let me know which call is throwing the exception?
- are you using the config to instantiate a `NetworkWithInputEncoding` and are there any implementation details you can divulge about how the kernel is called?
- there might be something wrong with the input / output buffer sizes and the illegal memory access -- being undefined behavior -- only surfaces with some code paths.

Cheers!

**Comment by Tom94** [comment] 2022-04-24 12:16
Closing on the assumption that the problem is solved by now. Please feel free to re-open and provide extra details if not.

**Closed** 2022-04-24 12:16 UTC
